### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by jankkm** [kekebo/FreeSMUG-Chromium-Updater#4]
Is the extension supposed to still work?
It is not anymore for me. It is looking for a new version forever.

**Comment by evanleck** [comment]
It looks like it might be trying to connect to https://www.freesmug.org/chromium which doesn't seem to have a valid certificate.

**Comment by evanleck** [comment]
Ah, nevermind. It's just a bit here https://github.com/p1g30n/chromium-updater/blob/master/js/popup.js#L110

**Comment by jmknoble** [comment]
Javascript console shows the problem:

> XMLHttpRequest cannot load https://sourceforge.net/projects/osxportableapps/files/Chromium/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://ccgjmadhdidfloacagcnnodbkedkjedg' is therefore not allowed access.

Looks like SourceForge doesn't have [cross-origin requests](http://www.w3.org/wiki/CORS_Enabled) enabled.  See this [quick explanation](https://github.com/MobileChromeApps/mobile-chrome-apps/issues/463).

**Comment by jmknoble** [comment]
Verified lack of `Access-Control-Allow-Origin` header in response (using LiveHTTPHeaders in Firefox):

```
https://sourceforge.net/projects/osxportableapps/rss?path=/Chromium

GET /projects/osxportableapps/rss?path=/Chromium HTTP/1.1
Host: sourceforge.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Cookie: VISITOR=...
Connection: keep-alive
Cache-Control: max-age=0

HTTP/1.1 200 OK
Server: nginx
Date: Fri, 11 Mar 2016 17:27:19 GMT
Content-Type: application/rss+xml; charset=UTF-8
Connection: close
Pragma: no-cache
Cache-Control: no-cache
X-UA-Compatible: IE=edge,chrome=1
X-Frame-Options: SAMEORIGIN
Set-Cookie: VISITOR=...
Set-Cookie: sourceforge=...
Content-Length: 104767
X-Content-Type-Options: nosniff
```

**Comment by jmknoble** [comment]
Wow.  Further investigation [reveals](https://developer.chrome.com/extensions/xhr) that the manifest is now incomplete, as SourceForge appears to be redirecting the query from http: to https:.  Also, the version check in js/background.js was malfunctioning.  The actual URL being checked was the project/files page, but the RSS feed is much cleaner; the whole getFreesmug() function needed cleanup.

**Comment by jmknoble** [comment]
Fork with working code is at [https://github.com/jmknoble/chromium-updater]() .  I've submitted a pull request, but it's not been responded to.  Version bumped to v0.1.1.1 in fork (I'm just using my git tree as a developer mode extension, no current plans to release fork as packaged extension).

**Comment by TaciteOFF** [comment]
Thanks for the effort @jmknoble, but your fork doesn't work either for me.

<img width="378" alt="capture d ecran 2016-03-27 a 13 13 29" src="https://cloud.githubusercontent.com/assets/11161632/14065140/b997e016-f41d-11e5-8963-ca315e10dc4a.png">

**Comment by thepigeonoftime** [comment]
Hi guys, I'm so sorry, I've been out of time and haven't logged in to my Github for ages. Got some time over easter and will hopefully also finally get a windows version down the line. As for the problem: Access-Control-Header was caused by Sourceforge (finally) switching to HTTPS and the manifest.json only being set to HTTP, blocking the extension from reading out the site. I've pushed a new version which should work.

**Comment by jmknoble** [comment]
@p1g30n: Looks like your change did not bump the version number in manifest.json.  I suggest you bump it to 0.1.2.0, since 0.1.1.1 is used by [my fork](https://github.com/jmknoble/chromium-updater). (Chromium only allows 4 version components, otherwise I would have used 0.1.1.0.1...).

**Comment by foss-** [comment]
Should the new version show up here? https://chrome.google.com/webstore/detail/chromium-updater/ccgjmadhdidfloacagcnnodbkedkjedg
Nothing so far.

**Comment by thepigeonoftime** [comment]
Thanks for the reminder, I was gonna wait if the new version works for all, as it seems to do, I pushed it to https://chrome.google.com/webstore/detail/chromium-updater/ccgjmadhdidfloacagcnnodbkedkjedg

**Comment by foss-** [comment]
fix confirmed. thanks a bunch!
Chromium Updater 0.1.1.2 working as expected.
