### ISSUE TITLE
Licensing Suggestion

### ISSUE THREAD

**Issue by howardroark2018** [kekebo/FreeSMUG-Chromium-Updater#6]
Oh! Not again, Please!!  GPL License for Chromium updater?? This wonderful software should have had a much more friendly and permissible license like the MIT or BSD or even Apache 2.0. Specially considering that this is an extension app for chromium which itself is licensed under the wonderful BSD. Another point is the fact that, this piece of application is meant as a no nonsense permissible no strings attached option to google chrome. So, why not take the better route to MIT or BSD? Moreover, BSD and MIT are also anyways compatible with GPL, so if a user wants to add GPL code to an application under a BSD or MIT license, they can, as these licenses are compatible. So, BSD /MIT is basically the superset of all Open Source licenses and are considered the mother of Open Source ideology.
What say?
Thanks for the excellent piece of work by the way! I just wish it was under a better license like chromium itself.

**Comment by thepigeonoftime** [comment]
I haven't given the license much thought when I wrote it, but you're right. I will update the license to something more permissible when I push the windows version. Thanks for the input.
