### ISSUE TITLE
OpenZip() failed with 131 error code

### ISSUE THREAD

**Issue by avikbis** [kekebo/FreeSMUG-Chromium-Updater#8]
![](http://i.imgur.com/TcyxUQI.png)

everytime i open chrome updater 2.1, always getting this issue.

**Comment by thepigeonoftime** [comment]
I think you've got the wrong repo, chrlauncher for windows is located here https://github.com/henrypp/chrlauncher/issues

**Comment by avikbis** [comment]
I have no idea how i made this mistake :S
sorry for troubling you :|

**Comment by thepigeonoftime** [comment]
all good :)
