### ISSUE TITLE
Some questions [solved]

### ISSUE THREAD

**Issue by ghost** [kekebo/FreeSMUG-Chromium-Updater#9]
So I've found this extension and also [this extension](https://github.com/Hallbin/extension.chromium-updater). I don't know which one to use. I'm on windows, and I'm not sure if the other extension is for windows chromium or not. I know this one is for mac os x chromium, and I could just modify this extension to get the windows updates and then use it for private use purposes, but what about that other extension? What's the difference between that extension and this one?

And a few more things - if the dev channel build of chromium has auto-update, will I really need either of these extensions? Because I could just do the dev channel and I'd have a version of chromium that auto-updates without any custom extensions. And finally, is the other updater extension actually that now-deleted "chromium updater" extension from the chrome web store (i believe the ID of that was hcmicnfbmcjhlbdohdmdhfjlbigkcddl)?

Thanks.

**Comment by thepigeonoftime** [comment]
My extension is purely for the Mac OS builds of freesmug.org, the internal update function broke at some point so it's mainly a fix.

For windows, there's chrlauncher that works quite well, you can find it here https://chromium.woolyss.com/#updater

If you mean by dev channel Chromium actually dev channel Chrome, there's a difference: https://askubuntu.com/questions/6253/whats-the-difference-between-google-chrome-and-or-chromium-what-are-the-advant

**Comment by ghost** [comment]
Thank you! Yeah, I got confused there with the dev channel, I thought on the chromium appspot download page it was referring to a dev channel for chromium, but I guess it was actually referring to the chrome dev channel, and there's no such thing for chromium. And do you have any info on [Hallbin/extension.chromium-updater](https://github.com/Hallbin/extension.chromium-updater)? It seems to also be in the form of a chromium extension, and I'm unsure of what it is, whether or not it works for Windows chromium (i use windows), and if it even still works. If it's broken or for mac only or you just can't give me any info on it, i'll use chrlauncher.

**Comment by thepigeonoftime** [comment]
Looking at the code it pulls automated windows builds from http://src.chromium.org/viewvc/chrome/branches/ while checking http://commondatastorage.googleapis.com/chromium-browser-snapshots/Win/LAST_CHANGE for version ( https://github.com/Hallbin/extension.chromium-updater/blob/master/popup.js ). 

So it's something like windows equivalent of my extension. chrlauncher has a few extra features:  https://github.com/henrypp/chrlauncher/

**Comment by ghost** [comment]
Thanks for the info! I'll try out your extension on my mac laptop, I'll try out chrlauncher on my windows desktop, and I'll also test out Hallbin's extension. Closing this now.
